#!/usr/bin/env bash
# Run as nginx as nginx
pkill -f apache2
sudo service nginx stop
chmod 644 /etc/nginx/nginx.conf
sed -i 's/user www-data;/user nginx;/g' /etc/nginx/nginx.conf
sed -i 's/80/8080/' /etc/nginx/sites-enabled/default
chown -R nginx:nginx /etc/nginx/nginx.conf
sudo -u nginx service nginx reload
sudo -u nginx service nginx restart
