#!/usr/bin/env bash
# Run nginx as nginx
pkill -f apache2
sudo service nginx stop
chmod 644 /etc/nginx/nginx.conf
sed -i "1i user nginx;" /etc/nginx/nginx.conf
sed -i 's/80/8080/' /etc/nginx/sites-enabled/default
chown -R nginx:nginx /etc/nginx/nginx.conf
sudo -u nginx service nginx reload
sudo -u nginx service nginx restart
